const DestData=[
    {
        id:0,
        img1:'https://www.keralatourism.org/images/microsites/munnar/munnar.jpg',
        img2:'https://www.keralatourism.org/images/microsites/munnar/munnar.jpg',
        img3:'',
        heading:'abx',
        text:'Hello 0 ',
        button:'See More',
    },
    {
        id:1,
        img1:'https://www.keralatourism.org/images/microsites/munnar/munnar.jpg',
        img2:'',
        img3:'',
        heading:'abx',
        text:'Hello 1 ',
        button:'See More',
    },
    {
        id:2,
        img1:'https://www.keralatourism.org/images/microsites/munnar/munnar.jpg',
        img2:'',
        img3:'',
        heading:'abx',
        text:'Hello 2',
        button:'See More',
    },
    {
        id:3,
        img1:'https://www.keralatourism.org/images/microsites/munnar/munnar.jpg',
        img2:'',
        img3:'',
        heading:'abx',
        text:'Hello 3',
        button:'See More',
    },
    {
        id:4,
        img1:'https://www.keralatourism.org/images/microsites/munnar/munnar.jpg',
        img2:'',
        img3:'',
        heading:'abx',
        text:'Hello 4',
        button:'See More',
    },
    {
        id:5,
        img1:'https://www.keralatourism.org/images/microsites/munnar/munnar.jpg',
        img2:'',
        img3:'',
        heading:'abx',
        text:'Hello 5 ',
        button:'See More',
    }
]
export default DestData